syntax enable

" Plugins
call plug#begin()

Plug 'cfdrake/vim-carthage'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'toyamarinyon/vim-swift'
Plug 'altercation/vim-colors-solarized'
Plug 'mattn/emmet-vim'
Plug 'thoughtbot/vim-rspec'

call plug#end()

" Themes
let g:solarized_termcolors=256
set background=dark
colorscheme solarized

" Mapping
nmap <leader>l :set list!<CR>

" Text editing
set tabstop=4
set softtabstop=0 noexpandtab
set shiftwidth=4
set tabstop=4 softtabstop=0 expandtab shiftwidth=4 smarttab

" Change cursor in Insert mode
if $TERM_PROGRAM =~ "iTerm"
    let &t_SI = "\<Esc>]50;CursorShape=1\x7" "vertical bar in insert mode
    let &t_EI = "\<Esc>]50;CursorShape=0\x7" "block in normal mode
endif

" File 
au BufRead,BufNewFile Gemfile setfiletype ruby
au BufRead,BufNewFile Dangerfile setfiletype ruby
au BufRead,BufNewFile Fastfile setfiletype ruby

" Ruby
function! Ruby()
    " Prevents @remi from judging you on Twitter
    " https://twitter.com/remi/status/767701379926331392
    set sts=2 sw=2 ts=2

    " RSpec.vim mappings
    map <Leader>t :call RunCurrentSpecFile()<CR>
    map <Leader>s :call RunNearestSpec()<CR>
    map <Leader>l :call RunLastSpec()<CR>
    map <Leader>a :call RunAllSpecs()<CR>
endfunction

autocmd FileType ruby call Ruby()
