syntax enable

" Plugins
call plug#begin()

Plug 'cfdrake/vim-carthage'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'toyamarinyon/vim-swift'
Plug 'altercation/vim-colors-solarized'
Plug 'mattn/emmet-vim'
Plug 'thoughtbot/vim-rspec'
Plug 'junegunn/vim-easy-align'

call plug#end()

" Themes
let g:solarized_termcolors=256
set background=dark
colorscheme solarized

" Mapping
nmap <leader>l :set list!<CR>

" Ctrl-p
let g:ctrlp_show_hidden = 1
map <Leader>, :CtrlPBuffer<CR>

" Change cursor in Insert mode
if $TERM_PROGRAM =~ "iTerm"
    let &t_SI = "\<Esc>]50;CursorShape=1\x7" "vertical bar in insert mode
    let &t_EI = "\<Esc>]50;CursorShape=0\x7" "block in normal mode
endif

autocmd BufRead,BufNewFile Gemfile set filetype=ruby
autocmd BufRead,BufNewFile Dangerfile set filetype=ruby
autocmd BufRead,BufNewFile Fastfile set filetype=ruby
autocmd BufRead,BufNewFile Podfile set filetype=ruby

au BufNewFile,BufRead *.markdown,*.md set filetype=markdown

" Align GitHub-flavored Markdown tables
au FileType markdown vmap <Leader><Bslash> :EasyAlign*<Bar><Enter>

" Prevents @remi from judging you on Twitter
" https://twitter.com/remi/status/767701379926331392
autocmd Filetype ruby setlocal expandtab tabstop=2 shiftwidth=2 softtabstop=2

